# https://mypy.readthedocs.io/en/latest/config_file.html#example-pyproject-toml
[tool.mypy]
no_silence_site_packages = true

[[tool.mypy.overrides]]
module = [
    "psse35",
    "psspy",
    "redirect",
    "tqdm"
]
ignore_missing_imports = true
